services:
  airflow:
    build: .
    container_name: airflow-sbp
    environment:
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin123
      - _AIRFLOW_WWW_USER_EMAIL=admin@example.com
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./spark_jobs:/opt/airflow/spark_jobs
    ports:
      - "8080:8080"
    command: standalone

  spark-master:
    image: apache/spark:3.4.1
    container_name: spark-master-sbp
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8081:8080"
    volumes:
      - ./data:/data
      - ./spark_jobs:/spark_jobs

  spark-worker:
    image: apache/spark:3.4.1
    container_name: spark-worker-sbp
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-sbp:7077
    depends_on:
      - spark-master
    volumes:
      - ./data:/data
      - ./spark_jobs:/spark_jobs